name: Build LaTeX document

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: RE4B-EN.tex
          args: -xelatex 
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: RE4B-EN
          path: |
            RE4B-EN.pdf
            RE4B-EN.log
